<template>
    <CardVue title="Tra cứu học phí">
        <template v-slot:body>
            <TableVue :columns="columns" :data="data" container-table-class="max-h-780px overflow-y-scroll" table-class="relative" :body-cell-class="bodyCellClass" :body-cell-span="bodyCellSpan" />
        </template>
    </CardVue>
</template>

<script setup>
import CardVue from '../components/Card.vue'
import TableVue from '../components/Table.vue'

const columns = [
    {
        key: 'stt',
        label: 'STT',
        cellClass: 'text-center',
        headClass: 'sticky -top-px',
    },
    {
        key: 'ma',
        label: 'Mã',
        cellClass: 'text-center',
        headClass: 'sticky -top-px',
    },
    {
        key: 'noiDung',
        label: 'Nội dung thu',
        cellClass: '',
        headClass: 'sticky -top-px',
    },
    {
        key: 'soTinChi',
        label: 'Số tín chỉ',
        cellClass: 'text-center',
        headClass: 'sticky -top-px',
    },
    {
        key: 'trangThaiDangKy',
        label: 'Trạng thái đăng ký',
        cellClass: '',
        headClass: 'sticky -top-px',
    },
    {
        key: 'soTien',
        label: 'Số tiền (VNĐ)',
        cellClass: 'text-right',
        headClass: 'sticky -top-px',
    },
    {
        key: 'daNop',
        label: 'Đã nộp (VNĐ)',
        cellClass: 'text-right',
        headClass: 'sticky -top-px',
    },
    {
        key: 'khauTru',
        label: 'Khấu trừ (VNĐ)',
        cellClass: 'text-center',
        headClass: 'sticky -top-px',
    },
    {
        key: 'congNo',
        label: 'Công nợ (VNĐ)',
        cellClass: 'text-right',
        headClass: 'sticky -top-px',
    },
    {
        key: 'trangThai',
        label: 'Trạng thái',
        cellClass: 'text-center',
        headClass: 'sticky -top-px',
    },
]
const data = [
    {
        stt: 1,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 2,
        ma: '418802',
        noiDung: 'Tư tưởng Hồ Chí Minh',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 3,
        ma: '468804',
        noiDung: 'Mạng máy tính	',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 4,
        ma: '478803',
        noiDung: 'Hệ cơ sở dữ liệu',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 5,
        ma: '478804',
        noiDung: 'Đồ án hệ cơ sở dữ liệu',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 6,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 7,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 8,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 9,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 10,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 1,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 2,
        ma: '418802',
        noiDung: 'Tư tưởng Hồ Chí Minh',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 3,
        ma: '468804',
        noiDung: 'Mạng máy tính	',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 4,
        ma: '478803',
        noiDung: 'Hệ cơ sở dữ liệu',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 5,
        ma: '478804',
        noiDung: 'Đồ án hệ cơ sở dữ liệu',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 6,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 7,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 8,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 9,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 10,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 1,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 2,
        ma: '418802',
        noiDung: 'Tư tưởng Hồ Chí Minh',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 3,
        ma: '468804',
        noiDung: 'Mạng máy tính	',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 4,
        ma: '478803',
        noiDung: 'Hệ cơ sở dữ liệu',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 5,
        ma: '478804',
        noiDung: 'Đồ án hệ cơ sở dữ liệu',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 6,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 7,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 8,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 9,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 10,
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: 0,
        daNop: 0,
        khauTru: '',
        congNo: '',
        trangThai: 'Đã nộp',
    },
    {
        stt: 'TỔNG:',
        ma: '408807',
        noiDung: 'Các mô hình toán',
        soTinChi: 3,
        trangThaiDangKy: 'Đăng ký mới',
        soTien: '6.918.000',
        daNop: '6.918.000',
        khauTru: '',
        congNo: '',
        trangThai: '',
    },
]
const bodyCellSpan = ({ row, columnKey, rowIndex }) => {
    const listFieldColspan1 = ['ma', 'noiDung', 'soTinChi', 'trangThaiDangKy']
    if (rowIndex === data.length - 1 && columnKey === 'stt') {
        return {
            colspan: 5,
            rowspan: 1,
        }
    } else if (rowIndex === data.length - 1 && listFieldColspan1.includes(columnKey)) {
        return {
            colspan: 0,
            rowspan: 0,
        }
    }

    return {
        rowspan: 1,
        colspan: 1,
    }
}

const bodyCellClass = ({ row, columnKey, rowIndex }) => {
    if (rowIndex === data.length - 1) {
        let className = 'bg-gray-100 '

        const listFields = ['soTien', 'daNop', 'khauTru', 'congNo']
        if (listFields.includes(columnKey)) {
            className += 'text-red-500 font-bold '
        } else if (columnKey === 'stt') {
            className += 'text-right font-bold text-blue-400 '
        }

        return className
    }
    return ''
}
</script>